=== Summary
API에서 지원하는 path에 대해서 알려드립니다

=== schema

=== [GET] /articles

==== Summary
존재하는 모든 아티클을 가져옴

==== API 요청 예시
operation::article-controller-test/get-all-articles/[snippets='curl-request,httpie-request']

==== HTTP 요청 및 응답 예시
operation::article-controller-test/get-all-articles/[snippets='http-request,http-response']

==== 요청 본문 및 응답 본문 예시
operation::article-controller-test/get-all-articles/[snippets='request-body,response-body']

=== [GET] /articles/{id}
==== Summary
id에 해당하는 Article을 작성함

==== API 요청 예시
operation::article-controller-test/get-by-id/[snippets='curl-request,httpie-request']

==== HTTP 요청 및 응답 예시
operation::article-controller-test/get-by-id/[snippets='http-request,http-response']

==== 요청 본문 및 응답 본문 예시
operation::article-controller-test/get-by-id/[snippets='request-body,response-body']

=== [POST] /articles
==== Summary
아티클을 작성함

==== API 요청 예시
operation::article-controller-test/post-article/[snippets='curl-request,httpie-request']

==== HTTP 요청 및 응답 예시
operation::article-controller-test/post-article/[snippets='http-request,http-response']

==== 요청 본문 및 응답 본문 예시
operation::article-controller-test/post-article/[snippets='request-body,response-body']

=== [POST] /articles/update
==== Summary
아티클을 작성함

==== API 요청 예시
operation::article-controller-test/test-post-article/[snippets='curl-request,httpie-request']

==== HTTP 요청 및 응답 예시
operation::article-controller-test/test-post-article/[snippets='http-request,http-response']

==== 요청 본문 및 응답 본문 예시
operation::article-controller-test/test-post-article/[snippets='request-body,response-body']
