create table if not exists articles (
      article_id bigint generated by default as identity,
      content varchar(255),
      primary key (article_id)
);

insert into articles (content) values
('Lorem ipsum dolor sit amet'),
('Random content for testing'),
('This is a sample article'),
('Another random text here'),
('Testing data insertion'),
('Content generation example'),
('Example of random data'),
('Database testing content'),
('SQL insert statement test'),
('Last random article');
